# general
tensorboard_dir: ./runs
checkpoints_dir: ./checkpoints
device: cuda:0
seed: 42

# model
hidden_size: 256
n_anchors: 4

#criterion
eos_coef: 0.5
cost_point: 0.05
reg_loss_weight: 0.0002

# optimization
lr: 0.0001
lr_backbone: 0.00001
lr_drop_epoch: 3500
lr_drop_gamma: 0.1
max_grad_norm: 0.1
weight_decay: 0.0001

# training
batch_size: 8
n_epochs: 3500
eval_freq: 5
patience: 50